modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
# ID тепер правильний і відповідає тому, що вказано в Java файлі
modId="nestworldvideo" 
version="1.0.0"
displayName="Video Nestworld"
authors="Igor" # Можете вказати своє ім'я
description='''
A mod that allows watching videos from a private host in-game.
'''

[[dependencies.nestworldvideo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"